# REUSE configuration file
# See https://reuse.software/spec/ for specification
version = 1

# Kubernetes manifests and Docker files
[[annotations]]
path = "Dockerfile.gpu"
"SPDX-FileCopyrightText" = "2025 Byron Williams"
"SPDX-License-Identifier" = "MIT"

[[annotations]]
path = "k8s/**"
"SPDX-FileCopyrightText" = "2025 Byron Williams"
"SPDX-License-Identifier" = "MIT"

# Monitoring configuration
[[annotations]]
path = "monitoring/**"
"SPDX-FileCopyrightText" = "2025 Byron Williams"
"SPDX-License-Identifier" = "MIT"
