# SPDX-FileCopyrightText: 2025 Byron Williams <byronawilliams@gmail.com>
# SPDX-License-Identifier: MIT
"""Pydantic validation for annotation schemas.

Provides runtime validation for annotation schemas following the pattern
from schema_utils/validation.py. Uses Pydantic v2 for field-level validation
with comprehensive error reporting.

Validation Functions:
    - validate_sample_metadata: Validates complete SampleMetadata records
    - validate_enrichment_data: Validates EnrichmentData fields
    - validate_original_file_metadata: Validates OriginalFileMetadata
    - validate_original_labels: Validates OriginalLabels
    - validate_enrichment_version: Validates EnrichmentVersion

Field Validators:
    - SampleIdValidator: 32-char hex sample IDs
    - FileHashValidator: SHA256 file hashes
    - ConfidenceValidator: 0.0-1.0 confidence scores
    - BboxValidator: COCO-format bounding boxes
    - DpiValidator: Positive integer DPI values
    - PixelDimensionsValidator: Positive integer pixel dimensions
    - IsoDateValidator: ISO 8601 date strings

Example:
    >>> from image_preprocessing_detector.annotation.schemas.validators import (
    ...     validate_sample_metadata,
    ...     ValidationResult,
    ... )
    >>>
    >>> sample_dict = {
    ...     "id": "abc123def456...",
    ...     "file_hash": "a1b2c3...",
    ...     ...
    ... }
    >>> result = validate_sample_metadata(sample_dict)
    >>> if not result.valid:
    ...     print(f"Errors: {result.errors}")
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field, field_validator


@dataclass
class ValidationResult:
    """Result of schema validation.

    Follows the pattern from schema_utils/validation.py.

    Attributes:
        valid: Whether validation passed
        errors: List of validation error messages
        warnings: List of non-fatal warning messages
    """

    valid: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ============================================================================
# Field Validators (Pydantic v2)
# ============================================================================


class SampleIdValidator(BaseModel):
    """Validates sample ID format.

    Sample IDs must be 32-character lowercase hexadecimal strings
    generated by compute_sample_id().
    """

    id: str = Field(..., min_length=32, max_length=32)

    @field_validator("id")
    @classmethod
    def validate_hex(cls, v: str) -> str:
        """Validate hexadecimal format."""
        if not re.match(r"^[a-f0-9]{32}$", v):
            raise ValueError("Sample ID must be 32-char lowercase hex")
        return v


class FileHashValidator(BaseModel):
    """Validates file hash format.

    File hashes must be 64-character lowercase hexadecimal strings
    (SHA256 without prefix).
    """

    file_hash: str = Field(..., min_length=64, max_length=64)

    @field_validator("file_hash")
    @classmethod
    def validate_sha256(cls, v: str) -> str:
        """Validate SHA256 format."""
        if not re.match(r"^[a-f0-9]{64}$", v):
            raise ValueError("File hash must be 64-char lowercase hex (SHA256)")
        return v


class ConfidenceValidator(BaseModel):
    """Validates confidence score range.

    Confidence scores must be in the range [0.0, 1.0].
    """

    confidence: float = Field(..., ge=0.0, le=1.0)


class BboxValidator(BaseModel):
    """Validates COCO-format bounding box.

    Bounding boxes must be [x, y, width, height] with non-negative
    x/y and positive width/height.
    """

    bbox: list[float] = Field(..., min_length=4, max_length=4)

    @field_validator("bbox")
    @classmethod
    def validate_bbox(cls, v: list[float]) -> list[float]:
        """Validate bbox format and values."""
        if len(v) != 4:
            raise ValueError("Bbox must have exactly 4 values")

        x, y, w, h = v

        if x < 0:
            raise ValueError(f"Bbox x must be non-negative, got {x}")
        if y < 0:
            raise ValueError(f"Bbox y must be non-negative, got {y}")
        if w <= 0:
            raise ValueError(f"Bbox width must be positive, got {w}")
        if h <= 0:
            raise ValueError(f"Bbox height must be positive, got {h}")

        return v


class DpiValidator(BaseModel):
    """Validates DPI values.

    DPI must be a positive integer.
    """

    dpi: int = Field(..., gt=0)


class PixelDimensionsValidator(BaseModel):
    """Validates pixel dimensions.

    Width and height must be positive integers.
    """

    width_px: int = Field(..., gt=0)
    height_px: int = Field(..., gt=0)


class IsoDateValidator(BaseModel):
    """Validates ISO 8601 date strings.

    Checks for basic ISO 8601 format (YYYY-MM-DD or with time).
    """

    date_str: str

    @field_validator("date_str")
    @classmethod
    def validate_iso_format(cls, v: str) -> str:
        """Validate ISO 8601 format."""
        # Basic ISO 8601 pattern (YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS...)
        pattern = (
            r"^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?)?$"
        )
        if not re.match(pattern, v):
            raise ValueError(f"Invalid ISO 8601 date format: {v}")
        return v


class MosScoreValidator(BaseModel):
    """Validates MOS (Mean Opinion Score) values.

    MOS scores typically range from 1.0 to 5.0 (DIQA, SmartDoc).
    """

    mos: float = Field(..., ge=1.0, le=5.0)


class OcrQualityScoreValidator(BaseModel):
    """Validates OCR quality scores.

    OCR quality scores range from 1 to 4 (1=best, inverted scale).
    """

    score: int = Field(..., ge=1, le=4)


# ============================================================================
# Validation Functions (follow schema_utils pattern)
# ============================================================================


def validate_sample_metadata(data: dict[str, Any]) -> ValidationResult:
    """Validate SampleMetadata dictionary.

    Validates required fields, field formats, and consistency.

    Args:
        data: Dictionary representation of SampleMetadata

    Returns:
        ValidationResult with valid flag, errors, and warnings
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Validate required fields
    required_fields = [
        "id",
        "file_hash",
        "dataset_name",
        "dataset_version",
        "original_path",
        "original_filename",
        "download_date",
        "original_labels",
        "original_file",
    ]

    for field_name in required_fields:
        if field_name not in data:
            errors.append(f"Missing required field: {field_name}")

    # Validate sample ID format
    if "id" in data:
        try:
            SampleIdValidator(id=data["id"])
        except Exception as e:
            errors.append(f"Invalid sample ID: {e}")

    # Validate file hash format
    if "file_hash" in data:
        try:
            FileHashValidator(file_hash=data["file_hash"])
        except Exception as e:
            errors.append(f"Invalid file hash: {e}")

    # Validate date format
    if "download_date" in data:
        try:
            IsoDateValidator(date_str=data["download_date"])
        except Exception as e:
            errors.append(f"Invalid download_date: {e}")

    if "created_at" in data:
        try:
            IsoDateValidator(date_str=data["created_at"])
        except Exception as e:
            errors.append(f"Invalid created_at: {e}")

    # Validate version numbers
    if "current_version" in data:
        current_version = data["current_version"]
        if not isinstance(current_version, int) or current_version < 0:
            errors.append(
                f"current_version must be non-negative int, got {current_version}"
            )

    # Validate enrichment versions
    if "enrichment_versions" in data:
        enrichment_versions = data["enrichment_versions"]
        if not isinstance(enrichment_versions, list):
            errors.append(
                f"enrichment_versions must be list, got {type(enrichment_versions)}"
            )
        else:
            for i, version in enumerate(enrichment_versions):
                result = validate_enrichment_version(version)
                for error in result.errors:
                    errors.append(f"enrichment_versions[{i}]: {error}")
                warnings.extend(result.warnings)

    # Validate nested objects
    if "original_labels" in data:
        result = validate_original_labels(data["original_labels"])
        for error in result.errors:
            errors.append(f"original_labels: {error}")
        warnings.extend(result.warnings)

    if "original_file" in data:
        result = validate_original_file_metadata(data["original_file"])
        for error in result.errors:
            errors.append(f"original_file: {error}")
        warnings.extend(result.warnings)

    # Warnings for missing optional but recommended fields
    if "schema_version" not in data:
        warnings.append("Missing schema_version - recommended for migration support")

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


def validate_enrichment_version(data: dict[str, Any]) -> ValidationResult:
    """Validate EnrichmentVersion dictionary.

    Args:
        data: Dictionary representation of EnrichmentVersion

    Returns:
        ValidationResult
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Validate required fields
    required_fields = ["version", "created_at", "created_by", "method", "description"]
    for field_name in required_fields:
        if field_name not in data:
            errors.append(f"Missing required field: {field_name}")

    # Validate version number
    if "version" in data:
        version = data["version"]
        if not isinstance(version, int) or version < 1:
            errors.append(f"version must be positive int, got {version}")

    # Validate timestamp
    if "created_at" in data:
        try:
            IsoDateValidator(date_str=data["created_at"])
        except Exception as e:
            errors.append(f"Invalid created_at: {e}")

    # Validate method is a valid EnrichmentTier value
    if "method" in data:
        method = data["method"]
        valid_methods = [
            "tier_0_exact",
            "tier_1_annotation",
            "tier_2_model",
            "tier_3_heuristic",
        ]
        if method not in valid_methods:
            warnings.append(f"method '{method}' not in standard EnrichmentTier values")

    # Validate data field
    if "data" in data:
        result = validate_enrichment_data(data["data"])
        for error in result.errors:
            errors.append(f"data: {error}")
        warnings.extend(result.warnings)

    # Warnings for missing reproducibility fields
    if "git_sha" not in data or data["git_sha"] is None:
        warnings.append("Missing git_sha - recommended for reproducibility")

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


def validate_enrichment_data(data: dict[str, Any]) -> ValidationResult:
    """Validate EnrichmentData dictionary.

    Args:
        data: Dictionary representation of EnrichmentData

    Returns:
        ValidationResult
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Validate confidence fields are in range [0.0, 1.0]
    confidence_fields = [
        "capture_confidence",
        "domain_confidence",
        "language_confidence",
        "paper_size_confidence",
        "llm_prediction_confidence",
    ]

    for field_name in confidence_fields:
        if field_name in data and data[field_name] is not None:
            try:
                ConfidenceValidator(confidence=data[field_name])
            except Exception as e:
                errors.append(f"{field_name}: {e}")

    # Validate quality_overall
    if "quality_overall" in data and data["quality_overall"] is not None:
        try:
            ConfidenceValidator(confidence=data["quality_overall"])
        except Exception as e:
            errors.append(f"quality_overall: {e}")

    # Validate DPI values
    if "resolution_dpi" in data and data["resolution_dpi"] is not None:
        try:
            DpiValidator(dpi=data["resolution_dpi"])
        except Exception as e:
            errors.append(f"resolution_dpi: {e}")

    # Validate pixel dimensions
    if "resolution_pixels" in data and data["resolution_pixels"] is not None:
        pixels = data["resolution_pixels"]
        if isinstance(pixels, (list, tuple)) and len(pixels) == 2:
            try:
                PixelDimensionsValidator(width_px=pixels[0], height_px=pixels[1])
            except Exception as e:
                errors.append(f"resolution_pixels: {e}")
        else:
            errors.append("resolution_pixels must be (width, height) tuple")

    # Validate MOS scores
    if "llm_predicted_mos" in data and data["llm_predicted_mos"] is not None:
        try:
            MosScoreValidator(mos=data["llm_predicted_mos"])
        except Exception as e:
            warnings.append(f"llm_predicted_mos: {e} (expected 1.0-5.0 range)")

    # Validate normalized predictions
    if (
        "llm_predicted_normalized" in data
        and data["llm_predicted_normalized"] is not None
    ):
        try:
            ConfidenceValidator(confidence=data["llm_predicted_normalized"])
        except Exception as e:
            errors.append(f"llm_predicted_normalized: {e}")

    # Validate layout detections
    if data.get("layout_detections"):
        if not isinstance(data["layout_detections"], list):
            errors.append("layout_detections must be a list")
        else:
            for i, det in enumerate(data["layout_detections"]):
                if not isinstance(det, dict):
                    errors.append(f"layout_detections[{i}] must be a dict")
                    continue

                # Validate bbox
                if "bbox" in det:
                    try:
                        BboxValidator(bbox=det["bbox"])
                    except Exception as e:
                        errors.append(f"layout_detections[{i}].bbox: {e}")

                # Validate confidence
                if "confidence" in det:
                    try:
                        ConfidenceValidator(confidence=det["confidence"])
                    except Exception as e:
                        errors.append(f"layout_detections[{i}].confidence: {e}")

                # Check required fields
                if "class_name" not in det:
                    errors.append(f"layout_detections[{i}]: missing class_name")
                if "source" not in det:
                    warnings.append(f"layout_detections[{i}]: missing source")

    # Validate text scope character/word counts
    if (
        "text_scope_estimated_chars" in data
        and data["text_scope_estimated_chars"] is not None
    ):
        chars = data["text_scope_estimated_chars"]
        if not isinstance(chars, int) or chars < 0:
            errors.append(
                f"text_scope_estimated_chars must be non-negative int, got {chars}"
            )

    if (
        "text_scope_estimated_words" in data
        and data["text_scope_estimated_words"] is not None
    ):
        words = data["text_scope_estimated_words"]
        if not isinstance(words, int) or words < 0:
            errors.append(
                f"text_scope_estimated_words must be non-negative int, got {words}"
            )

    # Validate paper size orientation
    if "paper_size_orientation" in data and data["paper_size_orientation"] is not None:
        orientation = data["paper_size_orientation"]
        if orientation not in ["portrait", "landscape"]:
            errors.append(
                f"paper_size_orientation must be 'portrait' or 'landscape', got {orientation}"
            )

    # Validate ISO codes if present
    if "iso639_language" in data and data["iso639_language"] is not None:
        lang = data["iso639_language"]
        # ISO 639-1 is 2 chars, ISO 639-3 is 3 chars
        if not re.match(r"^[a-z]{2,3}$", lang):
            warnings.append(
                f"iso639_language '{lang}' doesn't match ISO 639-1/3 format"
            )

    if "iso15924_script" in data and data["iso15924_script"] is not None:
        script = data["iso15924_script"]
        # ISO 15924 is 4 chars (e.g., "Latn", "Arab")
        if not re.match(r"^[A-Z][a-z]{3}$", script):
            warnings.append(
                f"iso15924_script '{script}' doesn't match ISO 15924 format"
            )

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


def validate_original_file_metadata(data: dict[str, Any]) -> ValidationResult:
    """Validate OriginalFileMetadata dictionary.

    Args:
        data: Dictionary representation of OriginalFileMetadata

    Returns:
        ValidationResult
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Validate required fields
    required_fields = [
        "format",
        "width_px",
        "height_px",
        "channels",
        "bit_depth",
        "file_size_bytes",
    ]

    for field_name in required_fields:
        if field_name not in data:
            errors.append(f"Missing required field: {field_name}")

    # Validate positive integer fields
    int_fields = {
        "width_px": "width",
        "height_px": "height",
        "channels": "channels",
        "bit_depth": "bit depth",
        "file_size_bytes": "file size",
    }

    for field_name in int_fields:
        if field_name in data and data[field_name] is not None:
            value = data[field_name]
            if not isinstance(value, int):
                errors.append(
                    f"{field_name} must be an integer, got {type(value).__name__}"
                )
            elif value <= 0:
                errors.append(f"{field_name} must be positive, got {value}")

    # Validate DPI if present
    if "dpi" in data and data["dpi"] is not None:
        try:
            DpiValidator(dpi=data["dpi"])
        except Exception as e:
            errors.append(f"dpi: {e}")

    # Validate format field
    if "format" in data:
        fmt = data["format"]
        if not isinstance(fmt, str) or not fmt:
            errors.append("format must be a non-empty string")
        else:
            # Common image formats (case-insensitive check)
            common_formats = ["png", "jpg", "jpeg", "tiff", "tif", "bmp", "gif", "webp"]
            if fmt.lower() not in common_formats:
                warnings.append(f"Uncommon image format: {fmt}")

    # Validate channels value
    if "channels" in data and data["channels"] is not None:
        channels = data["channels"]
        if channels not in [1, 3, 4]:
            warnings.append(f"Unusual channel count: {channels} (expected 1, 3, or 4)")

    # Validate bit depth
    if "bit_depth" in data and data["bit_depth"] is not None:
        bit_depth = data["bit_depth"]
        if bit_depth not in [1, 8, 16, 24, 32]:
            warnings.append(
                f"Unusual bit depth: {bit_depth} (expected 1, 8, 16, 24, or 32)"
            )

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


def validate_original_labels(data: dict[str, Any]) -> ValidationResult:
    """Validate OriginalLabels dictionary.

    Args:
        data: Dictionary representation of OriginalLabels

    Returns:
        ValidationResult
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Validate DIQA MOS scores (1-5 scale)
    diqa_mos_fields = [
        "diqa_overall",
        "diqa_sharpness",
        "diqa_color_fidelity",
        "diqa_mos",
    ]

    for field_name in diqa_mos_fields:
        if field_name in data and data[field_name] is not None:
            try:
                MosScoreValidator(mos=data[field_name])
            except Exception as e:
                errors.append(f"{field_name}: {e}")

    # Validate OCR quality score (1-4 scale, inverted)
    if "ocr_quality_score" in data and data["ocr_quality_score"] is not None:
        try:
            OcrQualityScoreValidator(score=data["ocr_quality_score"])
        except Exception as e:
            errors.append(f"ocr_quality_score: {e}")

    # Validate SmartDoc MOS
    if "smartdoc_mos" in data and data["smartdoc_mos"] is not None:
        try:
            MosScoreValidator(mos=data["smartdoc_mos"])
        except Exception as e:
            errors.append(f"smartdoc_mos: {e}")

    # Validate COCO annotations (must be lists)
    coco_annotation_fields = [
        "doclaynet_annotations",
        "tablebank_annotations",
        "pubtabnet_annotations",
    ]

    for field_name in coco_annotation_fields:
        if field_name in data and data[field_name] is not None:
            annotations = data[field_name]
            if not isinstance(annotations, list):
                errors.append(
                    f"{field_name} must be a list, got {type(annotations).__name__}"
                )
            else:
                # Validate each annotation has required COCO fields
                for i, ann in enumerate(annotations):
                    if not isinstance(ann, dict):
                        errors.append(f"{field_name}[{i}] must be a dict")
                        continue

                    # Check for bbox
                    if "bbox" in ann:
                        try:
                            BboxValidator(bbox=ann["bbox"])
                        except Exception as e:
                            errors.append(f"{field_name}[{i}].bbox: {e}")

    # Validate FUNSD annotations (must be dict, not list) - P0-4 fix
    if "funsd_annotations" in data and data["funsd_annotations"] is not None:
        annotations = data["funsd_annotations"]
        if not isinstance(annotations, dict):
            errors.append(
                f"funsd_annotations must be a dict (object), got {type(annotations).__name__}"
            )

    # Validate text instances (MLT-19 style)
    if "text_instances" in data and data["text_instances"] is not None:
        text_instances = data["text_instances"]
        if not isinstance(text_instances, list):
            errors.append(
                f"text_instances must be a list, got {type(text_instances).__name__}"
            )

    # Validate cell annotations
    if "cell_annotations" in data and data["cell_annotations"] is not None:
        cell_annotations = data["cell_annotations"]
        if not isinstance(cell_annotations, list):
            errors.append(
                f"cell_annotations must be a list, got {type(cell_annotations).__name__}"
            )

    # Validate boolean fields
    if "signatr_is_genuine" in data and data["signatr_is_genuine"] is not None:
        if not isinstance(data["signatr_is_genuine"], bool):
            errors.append("signatr_is_genuine must be a boolean")

    # Validate ISO language codes if present
    if "language_code" in data and data["language_code"] is not None:
        lang = data["language_code"]
        if not isinstance(lang, str) or len(lang) < 2:
            warnings.append(
                f"language_code '{lang}' doesn't appear to be a valid ISO code"
            )

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings,
    )


__all__ = [
    "BboxValidator",
    "ConfidenceValidator",
    "DpiValidator",
    "FileHashValidator",
    "IsoDateValidator",
    "MosScoreValidator",
    "OcrQualityScoreValidator",
    "PixelDimensionsValidator",
    "SampleIdValidator",
    "ValidationResult",
    "validate_enrichment_data",
    "validate_enrichment_version",
    "validate_original_file_metadata",
    "validate_original_labels",
    "validate_sample_metadata",
]
