"""Analysis module for comparing DeQA labeling approaches.

This module provides metrics and visualization for comparing labels
generated by different inference modes (specialist, ensemble, vl).
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
from scipy import stats

from image_preprocessing_detector.utils.datetime_compat import UTC

logger = logging.getLogger(__name__)


@dataclass
class ComparisonMetrics:
    """Metrics for comparing two label sets.

    Attributes:
        dimension: Quality dimension being compared.
        srcc: Spearman Rank Correlation Coefficient.
        plcc: Pearson Linear Correlation Coefficient.
        rmse: Root Mean Square Error.
        mae: Mean Absolute Error.
        sample_size: Number of samples compared.
        method_a: Name of first labeling method.
        method_b: Name of second labeling method.
    """

    dimension: str
    srcc: float
    plcc: float
    rmse: float
    mae: float
    sample_size: int
    method_a: str = ""
    method_b: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "dimension": self.dimension,
            "srcc": self.srcc,
            "plcc": self.plcc,
            "rmse": self.rmse,
            "mae": self.mae,
            "sample_size": self.sample_size,
            "method_a": self.method_a,
            "method_b": self.method_b,
        }


@dataclass
class VQualAScore:
    """VQualA 2025 Final Score calculation.

    The challenge uses weighted SRCC:
    Final Score = 0.5 * SRCC_overall + 0.25 * SRCC_sharpness + 0.25 * SRCC_color

    Attributes:
        overall_srcc: SRCC for overall quality dimension.
        sharpness_srcc: SRCC for sharpness dimension.
        color_srcc: SRCC for color dimension.
        final_score: Weighted final score.
    """

    overall_srcc: float
    sharpness_srcc: float
    color_srcc: float
    final_score: float = 0.0

    def __post_init__(self) -> None:
        """Calculate final score from dimension SRCCs."""
        self.final_score = (
            0.5 * self.overall_srcc
            + 0.25 * self.sharpness_srcc
            + 0.25 * self.color_srcc
        )

    def to_dict(self) -> dict[str, float]:
        """Serialize to dictionary."""
        return {
            "overall_srcc": self.overall_srcc,
            "sharpness_srcc": self.sharpness_srcc,
            "color_srcc": self.color_srcc,
            "final_score": self.final_score,
        }


@dataclass
class LabelAnalysis:
    """Complete analysis of a label set.

    Attributes:
        dataset: Dataset name.
        mode: Inference mode used.
        num_samples: Number of labeled samples.
        dimension_stats: Statistics per dimension.
        score_distribution: Distribution statistics.
    """

    dataset: str
    mode: str
    num_samples: int
    dimension_stats: dict[str, dict[str, float]] = field(default_factory=dict)
    score_distribution: dict[str, dict[str, float]] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "dataset": self.dataset,
            "mode": self.mode,
            "num_samples": self.num_samples,
            "dimension_stats": self.dimension_stats,
            "score_distribution": self.score_distribution,
        }


def load_labels(label_path: Path) -> list[dict]:
    """Load labels from JSONL file.

    Args:
        label_path: Path to JSONL label file.

    Returns:
        List of label dictionaries.

    Raises:
        ValueError: If path contains traversal attempts or is outside base directory.
        FileNotFoundError: If file does not exist.
    """
    # Validate path using Path.resolve() with base directory check
    resolved = label_path.resolve()
    base_dir = Path.cwd().resolve()

    # Check if resolved path is within base directory (prevents traversal attacks)
    try:
        resolved.relative_to(base_dir)
    except ValueError:
        msg = f"Path traversal not allowed: {label_path} resolves outside {base_dir}"
        raise ValueError(msg) from None

    if not resolved.is_file():
        msg = f"Label file not found: {resolved}"
        raise FileNotFoundError(msg)

    labels: list[dict] = []
    # Path validated above - resolved is safe to open
    with open(resolved) as f:  # nosemgrep: cli-path-traversal-open
        labels.extend(json.loads(line.strip()) for line in f)
    return labels


def compute_srcc(scores_a: list[float], scores_b: list[float]) -> float:
    """Compute Spearman Rank Correlation Coefficient.

    Args:
        scores_a: First set of scores.
        scores_b: Second set of scores.

    Returns:
        SRCC value.
    """
    if len(scores_a) < 2 or len(scores_b) < 2:
        return 0.0
    correlation, _ = stats.spearmanr(scores_a, scores_b)
    return float(correlation) if not np.isnan(correlation) else 0.0


def compute_plcc(scores_a: list[float], scores_b: list[float]) -> float:
    """Compute Pearson Linear Correlation Coefficient.

    Args:
        scores_a: First set of scores.
        scores_b: Second set of scores.

    Returns:
        PLCC value.
    """
    if len(scores_a) < 2 or len(scores_b) < 2:
        return 0.0
    correlation, _ = stats.pearsonr(scores_a, scores_b)
    return float(correlation) if not np.isnan(correlation) else 0.0


def compute_rmse(scores_a: list[float], scores_b: list[float]) -> float:
    """Compute Root Mean Square Error.

    Args:
        scores_a: First set of scores.
        scores_b: Second set of scores.

    Returns:
        RMSE value.
    """
    if not scores_a or not scores_b:
        return 0.0
    diff = np.array(scores_a) - np.array(scores_b)
    return float(np.sqrt(np.mean(diff**2)))


def compute_mae(scores_a: list[float], scores_b: list[float]) -> float:
    """Compute Mean Absolute Error.

    Args:
        scores_a: First set of scores.
        scores_b: Second set of scores.

    Returns:
        MAE value.
    """
    if not scores_a or not scores_b:
        return 0.0
    diff = np.abs(np.array(scores_a) - np.array(scores_b))
    return float(np.mean(diff))


def compare_label_sets(
    labels_a: list[dict],
    labels_b: list[dict],
    method_a: str = "method_a",
    method_b: str = "method_b",
) -> dict[str, ComparisonMetrics]:
    """Compare two label sets and compute metrics per dimension.

    Args:
        labels_a: First label set.
        labels_b: Second label set.
        method_a: Name for first method.
        method_b: Name for second method.

    Returns:
        Dictionary mapping dimension to ComparisonMetrics.
    """
    # Index labels by image path
    index_a = {label["image"]: label for label in labels_a}
    index_b = {label["image"]: label for label in labels_b}

    # Find common images
    common_images = set(index_a.keys()) & set(index_b.keys())
    logger.info("Found %d common images between label sets", len(common_images))

    if not common_images:
        logger.warning("No common images found between label sets")
        return {}

    # Collect scores per dimension
    dimensions = ["overall", "sharpness", "color"]
    dimension_scores: dict[str, tuple[list[float], list[float]]] = {
        dim: ([], []) for dim in dimensions
    }

    for image in common_images:
        scores_a = index_a[image].get("scores", {})
        scores_b = index_b[image].get("scores", {})

        for dim in dimensions:
            if dim in scores_a and dim in scores_b:
                dimension_scores[dim][0].append(scores_a[dim])
                dimension_scores[dim][1].append(scores_b[dim])

    # Compute metrics per dimension
    results = {}
    for dim, (scores_a, scores_b) in dimension_scores.items():
        if not scores_a:
            continue

        results[dim] = ComparisonMetrics(
            dimension=dim,
            srcc=compute_srcc(scores_a, scores_b),
            plcc=compute_plcc(scores_a, scores_b),
            rmse=compute_rmse(scores_a, scores_b),
            mae=compute_mae(scores_a, scores_b),
            sample_size=len(scores_a),
            method_a=method_a,
            method_b=method_b,
        )

    return results


def compare_to_ground_truth(
    labels: list[dict],
    ground_truth: list[dict],
    method_name: str = "predicted",
) -> dict[str, ComparisonMetrics]:
    """Compare labels to ground truth annotations.

    Args:
        labels: Predicted labels.
        ground_truth: Ground truth labels (e.g., DIQA-5000 MOS).
        method_name: Name for the prediction method.

    Returns:
        Dictionary mapping dimension to ComparisonMetrics.
    """
    return compare_label_sets(
        labels_a=ground_truth,
        labels_b=labels,
        method_a="ground_truth",
        method_b=method_name,
    )


def compute_vquala_score(
    metrics: dict[str, ComparisonMetrics],
) -> VQualAScore | None:
    """Compute VQualA 2025 Final Score from comparison metrics.

    Args:
        metrics: Comparison metrics per dimension.

    Returns:
        VQualAScore instance or None if metrics incomplete.
    """
    required_dims = ["overall", "sharpness", "color"]

    if not all(dim in metrics for dim in required_dims):
        missing = [dim for dim in required_dims if dim not in metrics]
        logger.warning("Missing dimensions for VQualA score: %s", missing)
        return None

    return VQualAScore(
        overall_srcc=metrics["overall"].srcc,
        sharpness_srcc=metrics["sharpness"].srcc,
        color_srcc=metrics["color"].srcc,
    )


def analyze_label_set(labels: list[dict]) -> LabelAnalysis:
    """Analyze a single label set.

    Args:
        labels: List of label dictionaries.

    Returns:
        LabelAnalysis with statistics.
    """
    if not labels:
        return LabelAnalysis(dataset="unknown", mode="unknown", num_samples=0)

    # Get metadata from first label
    first_label = labels[0]
    dataset = first_label.get("dataset", "unknown")
    mode = first_label.get("mode", "unknown")

    # Collect scores per dimension
    dimension_scores: dict[str, list[float]] = {}
    for label in labels:
        scores = label.get("scores", {})
        for dim, score in scores.items():
            if dim not in dimension_scores:
                dimension_scores[dim] = []
            dimension_scores[dim].append(score)

    # Compute statistics per dimension
    dimension_stats = {}
    score_distribution = {}

    for dim, scores in dimension_scores.items():
        if not scores:
            continue

        scores_arr = np.array(scores)
        dimension_stats[dim] = {
            "mean": float(np.mean(scores_arr)),
            "std": float(np.std(scores_arr)),
            "min": float(np.min(scores_arr)),
            "max": float(np.max(scores_arr)),
            "median": float(np.median(scores_arr)),
        }

        # Score distribution (1-5 scale bins)
        hist, _ = np.histogram(scores_arr, bins=[1, 2, 3, 4, 5, 6])
        total = len(scores_arr)
        score_distribution[dim] = {
            "1-2": int(hist[0]) / total,
            "2-3": int(hist[1]) / total,
            "3-4": int(hist[2]) / total,
            "4-5": int(hist[3]) / total,
        }

    return LabelAnalysis(
        dataset=dataset,
        mode=mode,
        num_samples=len(labels),
        dimension_stats=dimension_stats,
        score_distribution=score_distribution,
    )


def _format_dimension_stats(analysis: LabelAnalysis) -> list[str]:
    """Format dimension statistics for a label analysis.

    Args:
        analysis: LabelAnalysis with dimension_stats.

    Returns:
        List of formatted markdown lines.
    """
    lines = []
    for dim, dim_stats in analysis.dimension_stats.items():
        lines.append(
            f"**{dim.capitalize()}**: mean={dim_stats['mean']:.3f}, "
            f"std={dim_stats['std']:.3f}, range=[{dim_stats['min']:.2f}, {dim_stats['max']:.2f}]"
        )
    return lines


def _format_metrics_table(
    metrics: dict[str, ComparisonMetrics], include_samples: bool = False
) -> list[str]:
    """Format comparison metrics as a markdown table.

    Args:
        metrics: Dictionary of ComparisonMetrics per dimension.
        include_samples: Whether to include sample count column.

    Returns:
        List of markdown table lines.
    """
    lines = []
    if include_samples:
        lines.append("| Dimension | SRCC | PLCC | RMSE | MAE | Samples |")
        lines.append("|-----------|------|------|------|-----|---------|")
    else:
        lines.append("| Dimension | SRCC | PLCC | RMSE | MAE |")
        lines.append("|-----------|------|------|------|-----|")

    for dim in ["overall", "sharpness", "color"]:
        if dim in metrics:
            m = metrics[dim]
            if include_samples:
                lines.append(
                    f"| {dim.capitalize()} | {m.srcc:.4f} | {m.plcc:.4f} | "
                    f"{m.rmse:.4f} | {m.mae:.4f} | {m.sample_size} |"
                )
            else:
                lines.append(
                    f"| {dim.capitalize()} | {m.srcc:.4f} | {m.plcc:.4f} | "
                    f"{m.rmse:.4f} | {m.mae:.4f} |"
                )
    return lines


def _generate_ground_truth_section(
    specialist_labels: list[dict],
    ensemble_labels: list[dict],
    ground_truth: list[dict],
) -> list[str]:
    """Generate ground truth comparison section of the report.

    Args:
        specialist_labels: Labels from specialist mode.
        ensemble_labels: Labels from ensemble mode.
        ground_truth: Ground truth labels.

    Returns:
        List of markdown lines for ground truth section.
    """
    lines = [
        "",
        "## Comparison to Ground Truth",
        "",
        "### Specialist vs Ground Truth",
        "",
    ]

    specialist_gt_metrics = compare_to_ground_truth(
        specialist_labels, ground_truth, "specialist"
    )
    lines.extend(_format_metrics_table(specialist_gt_metrics))

    specialist_vquala = compute_vquala_score(specialist_gt_metrics)
    if specialist_vquala:
        lines.append(
            f"\n**Specialist VQualA Final Score: {specialist_vquala.final_score:.4f}**"
        )

    lines.extend(["", "### Ensemble vs Ground Truth", ""])

    ensemble_gt_metrics = compare_to_ground_truth(
        ensemble_labels, ground_truth, "ensemble"
    )
    lines.extend(_format_metrics_table(ensemble_gt_metrics))

    ensemble_vquala = compute_vquala_score(ensemble_gt_metrics)
    if ensemble_vquala:
        lines.append(
            f"\n**Ensemble VQualA Final Score: {ensemble_vquala.final_score:.4f}**"
        )

    # Expected VQualA 2025 champion score
    lines.extend(
        [
            "",
            "### Expected Performance (VQualA 2025)",
            "",
            "| Configuration | Final Score |",
            "|--------------|-------------|",
            "| Full ensemble (m0+m1+m3+Q0+Q1) | **0.9288** |",
            "| m1 (LoRA) | 0.9033 |",
            "| m0 (Full tune) | 0.8989 |",
        ]
    )

    return lines


def generate_comparison_report(
    specialist_labels: list[dict],
    ensemble_labels: list[dict],
    ground_truth: list[dict] | None = None,
    output_path: Path | None = None,
) -> str:
    """Generate a comparison report between specialist and ensemble labels.

    Args:
        specialist_labels: Labels from specialist mode.
        ensemble_labels: Labels from ensemble mode.
        ground_truth: Optional ground truth labels.
        output_path: Optional path to save report.

    Returns:
        Markdown report string.
    """
    report_lines = [
        "# DeQA Label Comparison Report",
        "",
        f"Generated: {datetime.now(tz=UTC).isoformat()}",
        "",
        "## Summary",
        "",
        f"- Specialist samples: {len(specialist_labels)}",
        f"- Ensemble samples: {len(ensemble_labels)}",
        "",
        "## Label Set Statistics",
        "",
        "### Specialist Mode",
        "",
    ]

    # Analyze and format label sets
    specialist_analysis = analyze_label_set(specialist_labels)
    ensemble_analysis = analyze_label_set(ensemble_labels)

    report_lines.extend(_format_dimension_stats(specialist_analysis))
    report_lines.extend(["", "### Ensemble Mode", ""])
    report_lines.extend(_format_dimension_stats(ensemble_analysis))

    # Compare specialist vs ensemble
    report_lines.extend(["", "## Specialist vs Ensemble Comparison", ""])

    comparison_metrics = compare_label_sets(
        specialist_labels,
        ensemble_labels,
        method_a="specialist",
        method_b="ensemble",
    )
    report_lines.extend(_format_metrics_table(comparison_metrics, include_samples=True))

    # Ground truth comparison if available
    if ground_truth:
        report_lines.extend(
            _generate_ground_truth_section(
                specialist_labels, ensemble_labels, ground_truth
            )
        )

    report_lines.extend(
        [
            "",
            "## Conclusions",
            "",
            "- Specialist mode uses 3 dimension-specific models for focused accuracy",
            "- Ensemble mode averages 5 VLM models for maximum correlation",
            "- Higher SRCC indicates better ranking correlation with ground truth",
            "",
        ]
    )

    report = "\n".join(report_lines)

    if output_path:
        output_path.write_text(report)
        logger.info("Report saved to %s", output_path)

    return report
