#!/usr/bin/env python3
"""Integrate all enrichment sources into DIQA-5000 Layer 2 metadata.

Merges 8 data sources into the main metadata JSON for all 5,500 records:
  1. Parser data (tier_0): capture_method, split, MOS scores
  2. LLM enrichment (tier_2, 500 ori/ images): domain, content flags, orientation
  3. Language enrichment (tier_2, 5,499 images): iso639, iso15924, script_family
  4. Egret-xlarge layout (tier_2, preferred): 17-class with per-detection confidence
  5. Docling GPU layout (tier_2, fallback): layout detections (COCO xywh)
  6. Docling GPU OCR (tier_2, 5,500 images): text_content, text_statistics
  7. Classical IQA (tier_2, optional): 8 detector scores (blur, noise, skew, etc.)
  8. Derived fields (tier_3): image_properties, paper_size, degradations

Layout priority: egret_xlarge > docling_gpu > DocLayout-YOLO (v1).
Creates a new enrichment version in each sample's enrichments.versions[].

Usage:
    PYTHONPATH=/home/byron/dev/image_detection:$PYTHONPATH \
        uv run python3 scripts/integrate_diqa_enrichments.py

    # Dry run (report only, no write):
    PYTHONPATH=... uv run python3 scripts/integrate_diqa_enrichments.py --dry-run

    # Custom paths:
    PYTHONPATH=... uv run python3 scripts/integrate_diqa_enrichments.py \
        --metadata /path/to/diqa-5000_metadata.json \
        --output /path/to/output.json
"""

# --- Level 4 registry metadata ---
from __future__ import annotations

__l4_category__      = 'integrate-script'
__l4_dataset__       = 'diqa-5000'
__l4_workstream__    = 'WS3'
__l4_parser__        = 'src/image_preprocessing_detector/annotation/parsers/quality/diqa.py'



import argparse
import csv
import json
import logging
import math
import re
import statistics
import time
from collections import Counter
from datetime import datetime, UTC
from pathlib import Path
from typing import Any

from image_preprocessing_detector.schema_utils.iso_language_script import (
    get_script_family as _get_script_family,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REGISTRY_DIR = Path("/mnt/e/image_detection/metadata_registry")
METADATA_PATH = REGISTRY_DIR / "json" / "diqa-5000_metadata.json"
LLM_ENRICHMENT_PATH = REGISTRY_DIR / "json" / "diqa-5000_llm_enrichment.json"
LANG_ENRICHMENT_PATH = REGISTRY_DIR / "json" / "diqa-5000_language_enrichment.json"
LAYOUT_BATCH_DIR = REGISTRY_DIR / "extracted" / "diqa-5000"
EGRET_BATCH_DIR = REGISTRY_DIR / "extracted" / "diqa-5000-egret"
OCR_BATCH_DIR = REGISTRY_DIR / "extracted" / "diqa-5000"
DATASET_DIR = Path("/mnt/e/image_detection/02_benchmark_only/diqa-5000")
ORPHAN_CORRECTIONS_PATH = Path(
    "scripts/audit/results/diqa-5000/orphan_corrections.json"
)

SCRIPT_VERSION = "2.1.0"
ENRICHMENT_VERSION_TAG = "integrated_v5"

# Classical IQA cache path (generated by --run-classical-iqa, loaded during integration)
IQA_CACHE_PATH = REGISTRY_DIR / "extracted" / "diqa-5000-classical-iqa.json"

# Content flag derivation from canonical layout classes
TABLE_CLASSES = {"TABLE"}
FORMULA_CLASSES = {"FORMULA"}
FIGURE_CLASSES = {"PICTURE", "CHART"}
CODE_CLASSES = {"CODE"}

# Docling layout category -> canonical class mapping (for content flag derivation)
DOCLING_CATEGORY_TO_CANONICAL: dict[str, str] = {
    "caption": "CAPTION",
    "checkbox_unselected": "CHECKBOX_UNSELECTED",
    "code": "CODE",
    "footnote": "FOOTNOTE",
    "formula": "FORMULA",
    "list_item": "LIST_ITEM",
    "picture": "PICTURE",
    "section_header": "SECTION_HEADER",
    "table": "TABLE",
    "text": "TEXT",
}

# Text-bearing classes for text_area_ratio computation
TEXT_REGION_CLASSES = {
    "TEXT",
    "LIST_ITEM",
    "SECTION_HEADER",
    "TITLE",
    "CAPTION",
    "FOOTNOTE",
}


# ---------------------------------------------------------------------------
# Derived field helpers
# ---------------------------------------------------------------------------
def derive_layout_category(
    detections: list[dict[str, Any]],
) -> tuple[str, float]:
    """Derive layout category (textual / tabular / mixed_content) from detections.

    Returns:
        Tuple of (category_name, confidence).
    """
    classes = [d.get("class", "").upper() for d in detections]
    has_table = any(c in TABLE_CLASSES for c in classes)
    has_figure = any(c in FIGURE_CLASSES for c in classes)
    has_formula = any(c in FORMULA_CLASSES for c in classes)

    if has_table and (has_figure or has_formula):
        return "mixed_content", 0.8
    if has_table:
        return "tabular", 0.85
    if has_figure or has_formula:
        return "mixed_content", 0.75
    return "textual", 0.9


def compute_text_area_ratio(
    detections: list[dict[str, Any]],
    img_w: int,
    img_h: int,
) -> float:
    """Compute ratio of text-region area to total image area."""
    total_image_area = img_w * img_h
    if total_image_area <= 0:
        return 0.0

    text_area = sum(
        d["bbox"][2] * d["bbox"][3]  # COCO xywh: w * h
        for d in detections
        if d.get("class", "").upper() in TEXT_REGION_CLASSES
        and isinstance(d.get("bbox"), list)
        and len(d["bbox"]) >= 4
    )
    return round(text_area / total_image_area, 4)


def check_split_leakage(
    res_to_ori: dict[str, str],
    split_map: dict[str, str],
) -> list[str]:
    """Check that no ori image appears in multiple splits.

    Args:
        res_to_ori: Mapping of res/ filename -> ori/ filename.
        split_map: Mapping of filename -> split name.

    Returns:
        List of ori/ filenames that leak across splits (should be empty).
    """
    ori_splits: dict[str, set[str]] = {}
    for res_filename, ori_filename in res_to_ori.items():
        split = split_map.get(res_filename)
        if split:
            ori_splits.setdefault(ori_filename, set()).add(split)

    return [ori for ori, splits in ori_splits.items() if len(splits) > 1]


# ---------------------------------------------------------------------------
# Classical IQA
# ---------------------------------------------------------------------------
def _extract_detector_fields(name: str, result: Any) -> dict[str, Any]:
    """Extract result fields from a single IQA detector into a flat dict.

    Args:
        name: Detector name (e.g. "skew", "blur").
        result: Detection result object.

    Returns:
        Dict of field-name -> value pairs for the detector.
    """
    _extractors: dict[str, Any] = {
        "skew": lambda r: {
            "skew_detected": r.is_skewed,
            "skew_angle": round(r.angle, 4),
            "skew_confidence": round(r.confidence, 4),
            "skew_severity": r.severity.value,
        },
        "blur": lambda r: {
            "blur_detected": r.is_blurred,
            "blur_score": round(r.blur_score, 4),
            "blur_confidence": round(r.confidence, 4),
            "blur_severity": r.severity.value,
        },
        "noise": lambda r: {
            "noise_detected": r.is_noisy,
            "noise_level": round(r.noise_sigma, 4),
            "noise_confidence": round(r.confidence, 4),
            "noise_severity": r.severity.value,
        },
        "contrast": lambda r: {
            "contrast_issue": r.is_low_contrast,
            "contrast_score": round(r.score, 4),
            "contrast_confidence": round(r.confidence, 4),
            "contrast_severity": r.severity.value,
        },
        "illumination": lambda r: {
            "illumination_issue": r.has_issues,
            "illumination_uniformity": round(r.score, 4),
            "illumination_confidence": round(r.confidence, 4),
            "illumination_severity": r.severity.value,
        },
        "jpeg_blockiness": lambda r: {
            "jpeg_blockiness_detected": r.has_artifacts,
            "jpeg_blockiness_score": round(r.blockiness_score, 4),
            "jpeg_blockiness_confidence": round(r.confidence, 4),
            "jpeg_blockiness_severity": r.severity.value,
        },
        "binarization": lambda r: {
            "binarization_quality": round(r.binarization_score, 4),
            "binarization_confidence": round(r.confidence, 4),
            "binarization_severity": r.severity.value,
        },
        "bleed_through": lambda r: {
            "bleed_through_detected": r.bleed_through_detected,
            "bleed_through_score": round(r.severity, 4),
            "bleed_through_confidence": round(r.confidence, 4),
            "bleed_through_severity": r.severity_level.value,
        },
    }
    extractor = _extractors.get(name)
    if extractor is None:
        return {}
    return extractor(result)


def run_classical_iqa_batch(
    metadata: dict[str, Any],
    dataset_dir: Path,
    output_path: Path,
) -> dict[str, dict[str, Any]]:
    """Run 8 classical IQA detectors on all images and cache results.

    This is the expensive step (~5-10ms/detector/image, ~40ms total per image).
    Results are cached to JSON so integration can re-run cheaply.

    Args:
        metadata: Full metadata dict with samples.
        dataset_dir: Root directory of the DIQA-5000 images.
        output_path: Path to write the IQA cache JSON.

    Returns:
        Dict mapping filename -> IQA results.
    """
    import cv2

    from image_preprocessing_detector.detection.iqa_classical import (
        BinarizationQualityDetector,
        BleedThroughDetector,
        BlurDetector,
        ContrastDetector,
        IlluminationDetector,
        JPEGBlockinessDetector,
        NoiseDetector,
        SkewDetector,
    )

    # Suppress verbose debug logging from IQA detectors during batch processing.
    # The detectors use structlog via get_logger(). The project's
    # configure_logging() isn't called in this script context, so structlog's
    # filter_by_level isn't active. We configure structlog here to filter
    # below WARNING and use minimal output.
    import structlog as _structlog

    _structlog.configure(
        processors=[
            _structlog.stdlib.filter_by_level,
            _structlog.stdlib.add_log_level,
            _structlog.dev.ConsoleRenderer(colors=False),
        ],
        context_class=dict,
        logger_factory=_structlog.stdlib.LoggerFactory(),
        cache_logger_on_first_use=False,  # allow level changes mid-session
    )
    logging.getLogger("image_preprocessing_detector").setLevel(logging.WARNING)

    # Initialize detectors once
    detectors = {
        "skew": SkewDetector(),
        "blur": BlurDetector(),
        "noise": NoiseDetector(),
        "contrast": ContrastDetector(),
        "illumination": IlluminationDetector(),
        "jpeg_blockiness": JPEGBlockinessDetector(),
        "binarization": BinarizationQualityDetector(),
        "bleed_through": BleedThroughDetector(),
    }

    results: dict[str, dict[str, Any]] = {}
    samples = metadata["samples"]
    total = len(samples)
    start = time.time()
    errors = 0

    log.info("Running classical IQA on %d images ...", total)

    for idx, sample in enumerate(samples):
        filename = sample["source"]["original_filename"]
        rel_path = sample["source"]["original_path"]
        img_path = dataset_dir / rel_path

        if not img_path.exists():
            log.warning("Image not found: %s", img_path)
            errors += 1
            continue

        img = cv2.imread(str(img_path))
        if img is None:
            log.warning("Failed to load image: %s", img_path)
            errors += 1
            continue

        sample_results: dict[str, Any] = {}

        for name, detector in detectors.items():
            try:
                result = detector.detect(img)
                sample_results.update(_extract_detector_fields(name, result))
            except Exception:
                log.exception("IQA %s failed for %s", name, filename)
                sample_results[f"{name}_error"] = True

        results[filename] = sample_results

        if (idx + 1) % 500 == 0:
            elapsed = time.time() - start
            rate = (idx + 1) / elapsed
            log.info(
                "  IQA [%d/%d] %.1f images/sec, %d errors",
                idx + 1,
                total,
                rate,
                errors,
            )

    elapsed = time.time() - start
    log.info(
        "Classical IQA complete: %d images in %.1f seconds (%.1f img/sec), %d errors",
        len(results),
        elapsed,
        len(results) / elapsed if elapsed > 0 else 0,
        errors,
    )

    # Restore log level
    logging.getLogger("image_preprocessing_detector").setLevel(logging.DEBUG)

    # Write cache
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as fh:
        json.dump(results, fh)
    log.info(
        "IQA cache written to %s (%.1f MB)",
        output_path,
        output_path.stat().st_size / 1024 / 1024,
    )

    return results


def load_classical_iqa_cache(path: Path) -> dict[str, dict[str, Any]]:
    """Load pre-computed classical IQA results from cache file.

    Args:
        path: Path to the IQA cache JSON.

    Returns:
        Dict mapping filename -> IQA results, or empty dict if not found.
    """
    if not path.exists():
        log.info("No classical IQA cache found at %s (use --run-classical-iqa)", path)
        return {}
    log.info("Loading classical IQA cache from %s ...", path)
    with open(path) as fh:
        data = json.load(fh)
    log.info("  Loaded IQA results for %d images", len(data))
    return data


# ---------------------------------------------------------------------------
# Data loaders
# ---------------------------------------------------------------------------
def load_metadata(path: Path) -> dict[str, Any]:
    """Load main metadata JSON."""
    log.info("Loading metadata from %s ...", path)
    with open(path) as fh:
        data = json.load(fh)
    log.info("  Loaded %d samples", len(data["samples"]))
    return data


def load_llm_enrichment(path: Path) -> dict[str, dict[str, Any]]:
    """Load LLM enrichment, indexed by original_filename."""
    log.info("Loading LLM enrichment from %s ...", path)
    with open(path) as fh:
        data = json.load(fh)

    index: dict[str, dict[str, Any]] = {}
    for sample in data["samples"]:
        # image_id is like "test_ori_00001", need "test_ori_00001.jpg"
        filename = sample["image_id"] + ".jpg"
        index[filename] = sample

    log.info("  Indexed %d LLM enrichment records", len(index))
    return index


def load_language_enrichment(path: Path) -> dict[str, dict[str, Any]]:
    """Load language enrichment, indexed by original_filename."""
    log.info("Loading language enrichment from %s ...", path)
    with open(path) as fh:
        data = json.load(fh)

    index: dict[str, dict[str, Any]] = {}
    for sample in data["samples"]:
        filename = sample["image_id"] + ".jpg"
        index[filename] = sample

    log.info("  Indexed %d language enrichment records", len(index))
    return index


def load_layout_batches(batch_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Load all Docling GPU layout batches, indexed by filename.

    Returns dict mapping filename -> list of annotation dicts (COCO xywh format).
    """
    log.info("Loading layout batches from %s ...", batch_dir)
    batch_files = sorted(batch_dir.glob("layout_batch_*.json"))
    if not batch_files:
        log.warning("  No layout batch files found!")
        return {}

    index: dict[str, list[dict[str, Any]]] = {}
    total_annotations = 0

    for bf in batch_files:
        with open(bf) as fh:
            batch = json.load(fh)

        # Build image_id -> filename mapping for this batch
        image_id_to_filename: dict[int, str] = {}
        for img in batch["images"]:
            image_id_to_filename[img["id"]] = img["file_name"]
            if img["file_name"] not in index:
                index[img["file_name"]] = []

        # Process annotations
        for ann in batch["annotations"]:
            img_id = ann["image_id"]
            filename = image_id_to_filename.get(img_id)
            if filename is None:
                continue

            # bbox is already in COCO [x, y, w, h] format per the batch schema
            detection = {
                "class_name": ann["category_name"],
                "bbox": ann["bbox"],
                "confidence": 1.0,  # Docling doesn't provide per-annotation confidence
                "source": "docling_gpu",
                "canonical_class": DOCLING_CATEGORY_TO_CANONICAL.get(
                    ann["category_name"], ann["category_name"].upper()
                ),
                "source_schema": "docling",
                "text_snippet": ann.get("text", "")[:200] if ann.get("text") else "",
            }
            index[filename].append(detection)
            total_annotations += 1

    log.info(
        "  Loaded %d annotations across %d images from %d batch files",
        total_annotations,
        len(index),
        len(batch_files),
    )
    return index


def load_egret_batches(batch_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Load egret-xlarge layout batches, indexed by filename.

    Returns dict mapping filename -> list of annotation dicts (COCO xywh format).
    Compatible with the layout_index format expected by integrate_sample().
    """
    log.info("Loading egret batches from %s ...", batch_dir)
    if not batch_dir.exists():
        log.warning("  Egret batch directory does not exist: %s", batch_dir)
        return {}

    batch_files = sorted(batch_dir.glob("egret_batch_*.json"))
    if not batch_files:
        log.warning("  No egret batch files found!")
        return {}

    index: dict[str, list[dict[str, Any]]] = {}
    total_annotations = 0

    for bf in batch_files:
        with open(bf) as fh:
            batch = json.load(fh)

        # Build image_id -> filename mapping for this batch
        image_id_to_filename: dict[int, str] = {}
        for img in batch["images"]:
            image_id_to_filename[img["id"]] = img["file_name"]
            if img["file_name"] not in index:
                index[img["file_name"]] = []

        # Process annotations - egret already has confidence + canonical_class
        for ann in batch["annotations"]:
            img_id = ann["image_id"]
            filename = image_id_to_filename.get(img_id)
            if filename is None:
                continue

            detection = {
                "class_name": ann.get("category_name", ""),
                "bbox": ann["bbox"],
                "confidence": ann.get("confidence", 0.9),
                "source": "egret_xlarge",
                "canonical_class": ann.get(
                    "canonical_class",
                    DOCLING_CATEGORY_TO_CANONICAL.get(
                        ann.get("category_name", ""), "UNKNOWN"
                    ),
                ),
                "source_schema": "docling",
                "text_snippet": "",
            }
            index[filename].append(detection)
            total_annotations += 1

    log.info(
        "  Loaded %d egret annotations across %d images from %d batch files",
        total_annotations,
        len(index),
        len(batch_files),
    )
    return index


def load_ocr_batches(batch_dir: Path) -> dict[str, dict[str, Any]]:
    """Load all Docling GPU OCR batches, indexed by filename.

    Returns dict mapping filename -> OCR record with text and metadata.
    """
    log.info("Loading OCR batches from %s ...", batch_dir)
    batch_files = sorted(batch_dir.glob("ocr_batch_*.jsonl"))
    if not batch_files:
        log.warning("  No OCR batch files found!")
        return {}

    index: dict[str, dict[str, Any]] = {}

    for bf in batch_files:
        with open(bf) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                # Extract filename from GCS path
                filename = record["source"].split("/")[-1]
                index[filename] = record

    log.info(
        "  Loaded %d OCR records from %d batch files", len(index), len(batch_files)
    )
    return index


def load_mos_scores(
    dataset_dir: Path,
) -> tuple[dict[str, dict[str, float]], dict[str, str]]:
    """Load MOS scores from all split CSVs.

    Returns:
        Tuple of:
        - mos_index: dict mapping filename -> {overall, sharpness, color_fidelity}
        - res_to_ori: dict mapping res filename -> ori filename
    """
    log.info("Loading MOS scores from %s ...", dataset_dir)
    mos_index: dict[str, dict[str, float]] = {}
    res_to_ori: dict[str, str] = {}

    for split in ["train", "val", "test"]:
        csv_path = dataset_dir / split / f"{split}.csv"
        if not csv_path.is_file():
            log.warning("  MOS CSV not found: %s", csv_path)
            continue

        with open(csv_path, newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                res_filename = row["res"].strip()
                ori_filename = row["ori"].strip()

                scores = {
                    "overall": float(row["overall"]),
                    "sharpness": float(row["sharpness"]),
                    "color_fidelity": float(row["color_fidelity"]),
                }

                # Index by res filename (the enhanced image)
                mos_index[res_filename] = scores

                # Build res->ori mapping for domain/language transfer
                res_to_ori[res_filename] = ori_filename

                # NOTE: ori/ images do NOT have MOS scores. MOS is only
                # collected for enhanced (res/) images. Do not assign
                # res/ scores to ori/ parents.

    log.info(
        "  Loaded MOS scores for %d images, %d res->ori mappings",
        len(mos_index),
        len(res_to_ori),
    )
    return mos_index, res_to_ori


# ---------------------------------------------------------------------------
# Text statistics computation
# ---------------------------------------------------------------------------
def compute_text_statistics(text: str) -> dict[str, Any]:
    """Compute basic text statistics from OCR output."""
    if not text or text.strip() == "":
        return {
            "char_count": 0,
            "word_count": 0,
            "line_count": 0,
            "has_content": False,
        }

    # Clean up image placeholders
    clean_text = text.replace("<!-- image -->", "").strip()

    lines = clean_text.split("\n")
    non_empty_lines = [ln for ln in lines if ln.strip()]
    words = clean_text.split()

    # Detect CJK characters (Chinese, Japanese, Korean)
    cjk_pattern = re.compile(
        r"[\u4e00-\u9fff\u3400-\u4dbf\u3000-\u303f\u3040-\u309f"
        r"\u30a0-\u30ff\uac00-\ud7af]"
    )
    cjk_chars = len(cjk_pattern.findall(clean_text))
    latin_words = len(re.findall(r"[a-zA-Z]+", clean_text))

    return {
        "char_count": len(clean_text),
        "word_count": len(words),
        "line_count": len(non_empty_lines),
        "cjk_char_count": cjk_chars,
        "latin_word_count": latin_words,
        "has_content": len(clean_text) > 0,
        "avg_line_length": round(statistics.mean(len(ln) for ln in non_empty_lines), 1)
        if non_empty_lines
        else 0,
    }


# ---------------------------------------------------------------------------
# Paper size estimation
# ---------------------------------------------------------------------------
def estimate_paper_size(
    width_px: int,
    height_px: int,
    dpi: int | None = None,
    capture_method: str | None = None,
) -> dict[str, Any]:
    """Estimate paper size from image dimensions.

    Args:
        width_px: Image width in pixels.
        height_px: Image height in pixels.
        dpi: Known DPI of the image.  Falls back to 300 if not provided.
        capture_method: How the image was captured (camera_smartphone, scanner, etc.).
            Phone captures have unreliable DPI since 300 refers to print
            resolution, not actual capture resolution.
    """
    effective_dpi = dpi if dpi and dpi > 0 else 300

    width_in = width_px / effective_dpi
    height_in = height_px / effective_dpi

    # Ensure width < height for comparison (portrait orientation)
    short = min(width_in, height_in)
    long_side = max(width_in, height_in)

    # Common paper sizes (width x height in inches, portrait)
    paper_sizes = {
        "A4": (8.27, 11.69),
        "Letter": (8.5, 11.0),
        "A3": (11.69, 16.54),
        "A5": (5.83, 8.27),
        "Legal": (8.5, 14.0),
        "B5": (6.93, 9.84),
    }

    best_match = "unknown"
    best_distance = float("inf")

    for name, (pw, ph) in paper_sizes.items():
        dist = math.sqrt((short - pw) ** 2 + (long_side - ph) ** 2)
        if dist < best_distance:
            best_distance = dist
            best_match = name

    # Base confidence from geometric match quality
    confidence = 0.6 if best_distance < 2.0 else 0.3

    result: dict[str, Any] = {
        "estimated_size": best_match,
        "estimated_width_in": round(width_in, 2),
        "estimated_height_in": round(height_in, 2),
        "assumed_dpi": effective_dpi,
        "confidence": confidence,
    }

    # Phone captures have unreliable DPI - 300 DPI fallback refers to
    # print resolution, not actual camera capture resolution
    if capture_method == "camera_smartphone" and not dpi:
        result["confidence"] = min(confidence, 0.5)
        result["estimation_note"] = (
            "DPI unknown for phone-captured image; using 300 DPI "
            "(print resolution) as approximation"
        )

    return result


def load_orphan_corrections(path: Path) -> dict[str, dict[str, Any]]:
    """Load manual corrections for orphan images, indexed by filename.

    Returns dict mapping filename -> corrections dict with field overrides.
    """
    if not path.exists():
        log.info("No orphan corrections file at %s", path)
        return {}

    log.info("Loading orphan corrections from %s ...", path)
    with open(path) as fh:
        data = json.load(fh)

    index: dict[str, dict[str, Any]] = {}
    for entry in data.get("corrections", []):
        corr = entry.get("corrections", {})
        # Single filename entry
        if "filename" in entry:
            index[entry["filename"]] = corr
        # Multi-filename entry
        for fn in entry.get("filenames", []):
            index[fn] = corr

    log.info("  Loaded corrections for %d images", len(index))
    return index


# ---------------------------------------------------------------------------
# Derive content flags from layout detections
# ---------------------------------------------------------------------------
def derive_content_flags(
    detections: list[dict[str, Any]],
) -> dict[str, bool]:
    """Derive content flags from canonical layout classes."""
    canonical_classes = {
        d.get("canonical_class", "").upper()
        for d in detections
        if d.get("canonical_class")
    }

    return {
        "has_table": bool(canonical_classes & TABLE_CLASSES),
        "has_formula": bool(canonical_classes & FORMULA_CLASSES),
        "has_figure": bool(canonical_classes & FIGURE_CLASSES),
        "has_code": bool(canonical_classes & CODE_CLASSES),
    }


# ---------------------------------------------------------------------------
# Derive physical degradation for ori/ images
# ---------------------------------------------------------------------------
def infer_ori_degradation_category(filename: str) -> str | None:
    """Infer distortion category for ori/ images from filename pattern.

    DIQA-5000 has 500 ori images across 5 distortion categories (100 each).
    Without explicit mapping, we can't determine which category from the filename alone.
    Returns None (requires lookup table or paper appendix).
    """
    # The paper doesn't provide a filename-to-distortion mapping
    # This would need to come from additional metadata
    return None


# ---------------------------------------------------------------------------
# MOS to quality tier mapping
# ---------------------------------------------------------------------------
def mos_to_quality_tier(overall_mos: float) -> str:
    """Map MOS overall score (1-5) to quality tier."""
    if overall_mos >= 4.0:
        return "high"
    if overall_mos >= 3.0:
        return "medium"
    if overall_mos >= 2.0:
        return "low"
    return "very_low"


def mos_to_normalized(mos: float) -> float:
    """Normalize MOS score from 1-5 to 0-1 range."""
    return round(max(0.0, min(1.0, (mos - 1.0) / 4.0)), 4)


# ---------------------------------------------------------------------------
# Reliability summary computation
# ---------------------------------------------------------------------------
def compute_reliability_summary(data: dict[str, Any]) -> dict[str, Any]:
    """Compute sample_reliability_summary for an enrichment data dict."""
    fields: list[dict[str, Any]] = []

    # Define field -> (confidence_key, tier) mappings
    field_defs = [
        ("capture_method", "capture_confidence", "capture_detection_method"),
        ("domain", "domain_confidence", None),
        ("language", "language_confidence", None),
        ("layout_detections", "layout_confidence", None),
        ("content_flags", "content_flags_confidence", None),
        ("text_quality", "text_quality_confidence", None),
        ("image_properties", "image_properties_confidence", None),
        ("geometric", "geometric_confidence", None),
        ("quality_scores", "quality_scores_confidence", None),
        ("text_content", "text_content_confidence", None),
    ]

    for field_name, conf_key, _method_key in field_defs:
        confidence = data.get(conf_key, 0.0)
        if confidence is None:
            confidence = 0.0

        # Categorize by confidence
        if confidence >= 0.9:
            category = "hard_label"
        elif confidence >= 0.7:
            category = "soft_label"
        elif confidence >= 0.5:
            category = "active_learning"
        else:
            category = "unreliable"

        fields.append(
            {
                "field": field_name,
                "confidence": round(confidence, 4),
                "category": category,
                "is_soft_label": category == "soft_label",
            }
        )

    min_field = min(fields, key=lambda f: f["confidence"])

    return {
        "min_confidence": min_field["confidence"],
        "min_confidence_field": min_field["field"],
        "min_confidence_category": min_field["category"],
        "assessed_field_count": len(fields),
        "hard_field_count": sum(1 for f in fields if f["category"] == "hard_label"),
        "soft_field_count": sum(1 for f in fields if f["category"] == "soft_label"),
        "field_summary": fields,
        "computed_at": datetime.now(UTC).isoformat(),
    }


# ---------------------------------------------------------------------------
# integrate_sample helpers (private)
# ---------------------------------------------------------------------------
def _resolve_llm_for_res(
    filename: str,
    is_res: bool,
    llm: dict[str, Any] | None,
    llm_index: dict[str, dict[str, Any]],
    res_to_ori: dict[str, str],
) -> dict[str, Any] | None:
    """Resolve the LLM enrichment dict, transferring from ori/ for res/ images."""
    if llm:
        return llm
    if is_res:
        ori_filename = res_to_ori.get(filename)
        return llm_index.get(ori_filename) if ori_filename else None
    return None


def _integrate_split(original_path: str) -> str:
    """Detect split from the original file path (D01)."""
    path_lower = original_path.lower()
    for split_name in ["train", "val", "test"]:
        if f"/{split_name}/" in path_lower or path_lower.startswith(f"{split_name}/"):
            return split_name
    return "unknown"


def _integrate_capture_method(is_ori: bool, is_res: bool) -> dict[str, Any]:
    """Determine capture method fields (D02)."""
    if is_ori:
        return {
            "capture_method": "camera_smartphone",
            "capture_confidence": 0.95,
            "capture_detection_method": "parser_dociq_paper",
        }
    if is_res:
        return {
            "capture_method": "synthetic",
            "capture_confidence": 1.0,
            "capture_detection_method": "parser_dociq_paper",
        }
    return {
        "capture_method": "unknown",
        "capture_confidence": 0.5,
        "capture_detection_method": "dataset_config",
    }


def _integrate_domain(
    llm: dict[str, Any] | None,
    is_res: bool,
    filename: str,
    llm_index: dict[str, dict[str, Any]],
    res_to_ori: dict[str, str],
) -> dict[str, Any]:
    """Integrate domain fields (D05)."""
    if llm:
        return {
            "domain_level1": llm["domain_level1"],
            "domain_confidence": llm["domain_confidence"],
            "domain_detection_method": "llm_vision",
            "domain_content_type": llm.get("content_type", ""),
        }
    if is_res:
        ori_filename = res_to_ori.get(filename)
        ori_llm = llm_index.get(ori_filename) if ori_filename else None
        if ori_llm:
            return {
                "domain_level1": ori_llm["domain_level1"],
                "domain_confidence": round(ori_llm["domain_confidence"] * 0.9, 4),
                "domain_detection_method": "llm_vision_transferred_from_ori",
                "domain_content_type": ori_llm.get("content_type", ""),
            }
    return {
        "domain_level1": "UNK",
        "domain_confidence": 0.3,
        "domain_detection_method": "none",
    }


def _integrate_language(
    llm: dict[str, Any] | None,
    lang: dict[str, Any] | None,
    is_res: bool,
    filename: str,
    lang_index: dict[str, dict[str, Any]],
    llm_index: dict[str, dict[str, Any]],
    res_to_ori: dict[str, str],
) -> dict[str, Any]:
    """Integrate language and script fields (D04, D06)."""
    _default = {
        "iso639_language": "und",
        "iso15924_script": "Zyyy",
        "language_confidence": 0.0,
        "text_scope_detection_method": "none",
    }

    if lang and lang.get("confidence", 0) >= 0.5:
        return {
            "iso639_language": lang["language"],
            "iso15924_script": lang["script"],
            "language_confidence": lang["confidence"],
            "text_scope_detection_method": "openlid_v2",
        }
    if llm:
        return {
            "iso639_language": llm.get("iso639_language", "und"),
            "iso15924_script": llm.get("iso15924_script", "Zyyy"),
            "language_confidence": 0.8,
            "text_scope_detection_method": "llm_vision",
        }
    if lang:
        return {
            "iso639_language": lang["language"],
            "iso15924_script": lang["script"],
            "language_confidence": lang["confidence"],
            "text_scope_detection_method": "openlid_v2_low_confidence",
        }
    if not is_res:
        return _default

    # Transfer language from ori counterpart via CSV mapping
    ori_filename = res_to_ori.get(filename)
    ori_lang = lang_index.get(ori_filename) if ori_filename else None
    ori_llm = llm_index.get(ori_filename) if ori_filename else None

    if ori_lang and ori_lang.get("confidence", 0) >= 0.5:
        return {
            "iso639_language": ori_lang["language"],
            "iso15924_script": ori_lang["script"],
            "language_confidence": round(ori_lang["confidence"] * 0.9, 4),
            "text_scope_detection_method": "openlid_v2_transferred_from_ori",
        }
    if ori_llm:
        return {
            "iso639_language": ori_llm.get("iso639_language", "und"),
            "iso15924_script": ori_llm.get("iso15924_script", "Zyyy"),
            "language_confidence": 0.7,
            "text_scope_detection_method": "llm_vision_transferred_from_ori",
        }
    return _default


def _integrate_layout(
    filename: str,
    egret_index: dict[str, list[dict[str, Any]]] | None,
    layout_index: dict[str, list[dict[str, Any]]],
    v1_data: dict[str, Any],
    width: int,
    height: int,
) -> dict[str, Any]:
    """Integrate layout detections with 3-tier priority (D07, D08)."""
    egret_dets = (egret_index or {}).get(filename, [])
    layout_dets = layout_index.get(filename, [])

    data: dict[str, Any] = {}

    if egret_dets:
        data.update(_layout_from_egret(egret_dets))
    elif layout_dets:
        data.update(_layout_from_docling(layout_dets))
    else:
        data.update(_layout_from_v1(v1_data))

    # Derive layout_category and text_area_ratio
    active_dets = data.get("layout_detections", [])
    if active_dets:
        layout_cat, layout_cat_conf = derive_layout_category(active_dets)
        data["layout_category"] = layout_cat
        data["layout_category_confidence"] = layout_cat_conf
        data["text_area_ratio"] = compute_text_area_ratio(active_dets, width, height)
    else:
        data["layout_category"] = "unknown"
        data["layout_category_confidence"] = 0.0
        data["text_area_ratio"] = 0.0

    return data


def _layout_from_egret(egret_dets: list[dict[str, Any]]) -> dict[str, Any]:
    """Build layout fields from egret-xlarge detections."""
    n_dets = len(egret_dets)
    high_conf = sum(1 for d in egret_dets if d.get("confidence", 0.9) >= 0.5)
    calibrated_conf = 0.70 + 0.15 * (high_conf / n_dets) if n_dets else 0.60
    flags = derive_content_flags(egret_dets)
    return {
        "layout_detections": egret_dets,
        "layout_source": "egret_xlarge",
        "layout_confidence": round(calibrated_conf, 4),
        "layout_detection_count": n_dets,
        "has_table": flags["has_table"],
        "has_formula": flags["has_formula"],
        "has_figure": flags["has_figure"],
        "has_code": flags["has_code"],
        "content_flags_tier": "tier_2_model",
        "content_flags_source": "egret_xlarge",
        "content_flags_confidence": round(calibrated_conf, 4),
    }


def _layout_from_docling(layout_dets: list[dict[str, Any]]) -> dict[str, Any]:
    """Build layout fields from Docling GPU detections."""
    flags = derive_content_flags(layout_dets)
    return {
        "layout_detections": layout_dets,
        "layout_source": "docling_gpu",
        "layout_confidence": 0.85,
        "layout_detection_count": len(layout_dets),
        "has_table": flags["has_table"],
        "has_formula": flags["has_formula"],
        "has_figure": flags["has_figure"],
        "has_code": flags["has_code"],
        "content_flags_tier": "tier_2_model",
        "content_flags_source": "docling_gpu",
        "content_flags_confidence": 0.85,
    }


def _layout_from_v1(v1_data: dict[str, Any]) -> dict[str, Any]:
    """Build layout fields from v1 (DocLayout-YOLO) fallback."""
    v1_layout = v1_data.get("layout_detections", [])
    source = v1_data.get("content_flags_source", "doclayout_yolo")
    flags = derive_content_flags(v1_layout)
    return {
        "layout_detections": v1_layout,
        "layout_source": source,
        "layout_confidence": 0.7,
        "layout_detection_count": len(v1_layout),
        "has_table": flags["has_table"],
        "has_formula": flags["has_formula"],
        "has_figure": flags["has_figure"],
        "has_code": flags["has_code"],
        "content_flags_tier": "tier_2_model",
        "content_flags_source": source,
        "content_flags_confidence": 0.7,
    }


def _override_content_flags_from_llm(
    data: dict[str, Any],
    llm_for_flags: dict[str, Any] | None,
) -> None:
    """Override content flags with LLM data (more reliable for handwriting)."""
    if not llm_for_flags:
        data["has_handwriting"] = data.get("has_handwriting", False)
        return

    data["has_handwriting"] = (
        True
        if llm_for_flags.get("has_handwriting")
        else data.get("has_handwriting", False)
    )
    if llm_for_flags.get("has_table"):
        data["has_table"] = True
    if llm_for_flags.get("has_formula"):
        data["has_formula"] = True
    if llm_for_flags.get("has_figure"):
        data["has_figure"] = True
    if llm_for_flags.get("has_signature"):
        data["has_signature"] = True


def _integrate_text_content(
    ocr: dict[str, Any] | None,
) -> dict[str, Any]:
    """Integrate text content and statistics from OCR (D14, D15)."""
    data: dict[str, Any] = {}

    if ocr and ocr.get("success") and ocr.get("text"):
        data["text_content"] = ocr["text"]
        data["text_content_confidence"] = ocr.get("confidence", 0.8)
        data["text_content_source"] = "docling_gpu_ocr"
        data["text_statistics"] = compute_text_statistics(ocr["text"])
    else:
        data["text_content"] = ""
        data["text_content_confidence"] = 0.0
        data["text_content_source"] = "none"
        data["text_statistics"] = compute_text_statistics("")

    text_stats = data["text_statistics"]
    if text_stats["has_content"]:
        data["text_quality_confidence"] = min(data["text_content_confidence"], 0.8)
        data["text_quality_method"] = "docling_ocr"
        data["text_quality_provenance_tier"] = "tier_2_model"
    else:
        data["text_quality_confidence"] = 0.0
        data["text_quality_method"] = "none"
        data["text_quality_provenance_tier"] = "tier_3_heuristic"

    return data


def _integrate_quality_scores(
    mos: dict[str, float] | None,
    is_ori: bool,
    is_res: bool,
) -> dict[str, Any]:
    """Integrate MOS quality scores (D09)."""
    if mos and is_res:
        return {
            "quality_overall_mos": mos["overall"],
            "quality_sharpness_mos": mos["sharpness"],
            "quality_color_fidelity_mos": mos["color_fidelity"],
            "quality_overall_normalized": mos_to_normalized(mos["overall"]),
            "quality_tier": mos_to_quality_tier(mos["overall"]),
            "quality_scores_confidence": 0.95,
            "quality_scores_source": "human_mos_itur_bt500",
        }
    if is_ori:
        return {
            "quality_overall_mos": None,
            "quality_sharpness_mos": None,
            "quality_color_fidelity_mos": None,
            "quality_scores_confidence": 0.0,
            "quality_scores_source": "none",
            "quality_mos_note": (
                "ori/ images are source degraded images without MOS scores"
            ),
        }
    return {
        "quality_scores_confidence": 0.0,
        "quality_scores_source": "none",
    }


def _integrate_geometric(
    llm_for_geo: dict[str, Any] | None,
    llm: dict[str, Any] | None,
    width: int,
    height: int,
) -> dict[str, Any]:
    """Integrate geometric / orientation properties (D10)."""
    if llm_for_geo and llm_for_geo.get("orientation"):
        orientation_str = llm_for_geo["orientation"]
        orientation_class = 90 if orientation_str == "landscape" else 0
        return {
            "orientation_class": orientation_class,
            "geometric_confidence": 0.85 if llm else 0.75,
            "geometric_source": (
                "llm_vision" if llm else "llm_vision_transferred_from_ori"
            ),
        }
    # Default: assume portrait based on dimensions
    return {
        "orientation_class": 0 if width < height else 90,
        "geometric_confidence": 0.6,
        "geometric_source": "dimension_heuristic",
    }


def _integrate_degradation(is_ori: bool) -> dict[str, Any]:
    """Integrate physical degradation info (D11)."""
    if is_ori:
        return {
            "physical_degradation_present": True,
            "physical_degradation_types": ["unknown_single_distortion"],
            "physical_degradation_note": (
                "Each DIQA-5000 ori/ image has exactly ONE distortion type "
                "(shadow, occlusion, blur, creases, or moire) but the per-image "
                "assignment is not provided in the public dataset. "
                "100 images per distortion type across 500 ori/ images."
            ),
            "physical_degradation_confidence": 0.5,
        }
    return {
        "physical_degradation_present": False,
        "physical_degradation_types": [],
        "physical_degradation_confidence": 0.9,
    }


def _integrate_handwriting(
    llm_for_hw: dict[str, Any] | None,
    llm: dict[str, Any] | None,
) -> dict[str, Any]:
    """Integrate handwriting assessment (D16)."""
    if llm_for_hw:
        return {
            "handwriting_present": llm_for_hw.get("has_handwriting", False),
            "handwriting_confidence": 0.85 if llm else 0.75,
            "handwriting_source": (
                "llm_vision" if llm else "llm_vision_transferred_from_ori"
            ),
        }
    return {
        "handwriting_present": False,
        "handwriting_confidence": 0.5,
        "handwriting_source": "none",
    }


def _integrate_llm_scores(
    llm_for_scores: dict[str, Any] | None,
    llm: dict[str, Any] | None,
) -> dict[str, Any]:
    """Integrate raw LLM enrichment scores (D18)."""
    if llm_for_scores:
        return {
            "llm_domain_level1": llm_for_scores.get("domain_level1"),
            "llm_domain_confidence": llm_for_scores.get("domain_confidence"),
            "llm_language": llm_for_scores.get("iso639_language"),
            "llm_script": llm_for_scores.get("iso15924_script"),
            "llm_content_type": llm_for_scores.get("content_type"),
            "llm_reasoning": llm_for_scores.get("reasoning", "")[:500],
            "llm_model": llm_for_scores.get("model_used"),
            "llm_data_available": True,
            "llm_data_is_direct": llm is not None,
        }
    return {
        "llm_data_available": False,
        "llm_data_is_direct": False,
    }


def _integrate_classical_iqa(iqa: dict[str, Any] | None) -> dict[str, Any]:
    """Integrate classical IQA scores into prefixed fields (D20)."""
    if not iqa:
        return {}

    _iqa_field_keys = [
        "skew_detected",
        "skew_angle",
        "skew_confidence",
        "skew_severity",
        "blur_detected",
        "blur_score",
        "blur_confidence",
        "blur_severity",
        "noise_detected",
        "noise_level",
        "noise_confidence",
        "noise_severity",
        "contrast_issue",
        "contrast_score",
        "contrast_confidence",
        "contrast_severity",
        "illumination_issue",
        "illumination_uniformity",
        "illumination_confidence",
        "illumination_severity",
        "jpeg_blockiness_detected",
        "jpeg_blockiness_score",
        "jpeg_blockiness_confidence",
        "jpeg_blockiness_severity",
        "binarization_quality",
        "binarization_confidence",
        "binarization_severity",
        "bleed_through_detected",
        "bleed_through_score",
        "bleed_through_confidence",
        "bleed_through_severity",
    ]
    data: dict[str, Any] = {
        f"classical_iqa_{key}": iqa.get(key) for key in _iqa_field_keys
    }
    data["classical_iqa_source"] = "iqa_classical_v1"
    data["classical_iqa_detector_count"] = 8

    if iqa.get("skew_angle") is not None:
        data["skew_angle_degrees"] = iqa["skew_angle"]

    return data


# ---------------------------------------------------------------------------
# Main integration logic
# ---------------------------------------------------------------------------
def integrate_sample(
    sample: dict[str, Any],
    llm_index: dict[str, dict[str, Any]],
    lang_index: dict[str, dict[str, Any]],
    layout_index: dict[str, list[dict[str, Any]]],
    ocr_index: dict[str, dict[str, Any]],
    mos_index: dict[str, dict[str, float]],
    res_to_ori: dict[str, str],
    egret_index: dict[str, list[dict[str, Any]]] | None = None,
    orphan_corrections: dict[str, dict[str, Any]] | None = None,
    iqa_index: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Create integrated enrichment data for a single sample.

    Returns a new enrichment version data dict with all sources merged.
    Layout priority: egret_xlarge > docling_gpu > v1 (DocLayout-YOLO).
    """
    filename = sample["source"]["original_filename"]
    original_path = sample["source"]["original_path"]
    width = sample["original_file"]["width_px"]
    height = sample["original_file"]["height_px"]
    dpi = sample["original_file"].get("dpi")

    is_ori = "/ori/" in original_path
    is_res = "/res/" in original_path

    # Get existing v1 data as baseline
    v1_data = {}
    if sample["enrichments"]["versions"]:
        v1_data = sample["enrichments"]["versions"][0].get("data", {})

    llm = llm_index.get(filename)
    lang = lang_index.get(filename)

    data: dict[str, Any] = {}

    # 1. Split (D01)
    data["split"] = _integrate_split(original_path)

    # 2. Capture method (D02)
    data.update(_integrate_capture_method(is_ori, is_res))

    # 3. Resolution
    data["resolution_category"] = v1_data.get("resolution_category", "unknown")
    data["resolution_pixels"] = [width, height]

    # 4. Domain (D05)
    data.update(_integrate_domain(llm, is_res, filename, llm_index, res_to_ori))

    # 5. Language & script (D04, D06)
    data.update(
        _integrate_language(
            llm, lang, is_res, filename, lang_index, llm_index, res_to_ori
        )
    )
    data["script_family"] = _get_script_family(data.get("iso15924_script", ""))

    # 6. Layout detections (D07, D08)
    data.update(
        _integrate_layout(filename, egret_index, layout_index, v1_data, width, height)
    )

    # Override content flags with LLM data
    llm_for_flags = _resolve_llm_for_res(
        filename,
        is_res,
        llm,
        llm_index,
        res_to_ori,
    )
    _override_content_flags_from_llm(data, llm_for_flags)

    # 7. Text content & statistics (D14, D15)
    data.update(_integrate_text_content(ocr_index.get(filename)))

    # 8. Quality scores (D09)
    data.update(_integrate_quality_scores(mos_index.get(filename), is_ori, is_res))

    # 9. Geometric properties (D10)
    llm_for_geo = _resolve_llm_for_res(filename, is_res, llm, llm_index, res_to_ori)
    data.update(_integrate_geometric(llm_for_geo, llm, width, height))

    # 10. Physical degradation (D11)
    data.update(_integrate_degradation(is_ori))

    # 11. Image properties (D13)
    data["image_properties_color_mode"] = "color"
    data["image_properties_document_age"] = "modern"
    data["image_properties_confidence"] = 0.95
    data["image_properties_source"] = "dataset_paper_ground_truth"

    # 12. Paper size (D17)
    data["paper_size"] = estimate_paper_size(
        width,
        height,
        dpi,
        capture_method=data.get("capture_method"),
    )

    # 13. Handwriting assessment (D16)
    llm_for_hw = _resolve_llm_for_res(filename, is_res, llm, llm_index, res_to_ori)
    data.update(_integrate_handwriting(llm_for_hw, llm))

    # 14. LLM scores integration (D18)
    llm_for_scores = _resolve_llm_for_res(filename, is_res, llm, llm_index, res_to_ori)
    data.update(_integrate_llm_scores(llm_for_scores, llm))

    # 15. Dataset short code
    data["dataset_short_code"] = "diqa-5000"

    # 16. Text scope
    data["text_scope_content_type"] = "printed"
    if data.get("has_handwriting"):
        data["text_scope_content_type"] = "mixed"

    # 17. Classical IQA scores (D20)
    data.update(_integrate_classical_iqa((iqa_index or {}).get(filename)))

    # Apply orphan corrections (manual overrides for missing enrichments)
    if orphan_corrections and filename in orphan_corrections:
        data.update(orphan_corrections[filename])

    # Compute reliability summary
    data["sample_reliability_summary"] = compute_reliability_summary(data)

    return data


def _track_source_matches(
    stats: dict[str, int],
    filename: str,
    llm_index: dict[str, dict[str, Any]],
    lang_index: dict[str, dict[str, Any]],
    layout_index: dict[str, list[dict[str, Any]]],
    ocr_index: dict[str, dict[str, Any]],
    mos_index: dict[str, dict[str, float]],
    egret_index: dict[str, list[dict[str, Any]]] | None,
    iqa_index: dict[str, dict[str, Any]] | None,
) -> None:
    """Increment source match counters for a single sample."""
    _match_keys = [
        ("llm_matched", llm_index),
        ("lang_matched", lang_index),
        ("layout_matched", layout_index),
        ("ocr_matched", ocr_index),
        ("mos_matched", mos_index),
    ]
    for key, index in _match_keys:
        if filename in index:
            stats[key] += 1
    if (egret_index or {}).get(filename):
        stats["egret_matched"] += 1
    if (iqa_index or {}).get(filename):
        stats["iqa_matched"] += 1


def _track_distribution_stats(
    stats: dict[str, int],
    integrated_data: dict[str, Any],
) -> None:
    """Track distribution counters from integrated data."""
    lang_method = integrated_data.get("text_scope_detection_method", "none")
    stats[f"lang_source_{lang_method}"] += 1
    domain_method = integrated_data.get("domain_detection_method", "none")
    stats[f"domain_source_{domain_method}"] += 1
    split_val = integrated_data.get("split", "unknown")
    stats[f"split_{split_val}"] += 1
    rel = integrated_data.get("sample_reliability_summary", {})
    cat = rel.get("min_confidence_category", "unreliable")
    stats[f"reliability_{cat}"] += 1


def _apply_sample_enrichment(
    sample: dict[str, Any],
    integrated_data: dict[str, Any],
) -> None:
    """Write integrated data back into the sample (mutates sample)."""
    # Fix split in source (D01)
    if integrated_data.get("split") != "unknown":
        sample["source"]["split"] = integrated_data["split"]

    # Fix original_labels with MOS scores (D03)
    if integrated_data.get("quality_overall_mos"):
        labels = sample.setdefault("original_labels", {})
        labels["mos_overall"] = integrated_data["quality_overall_mos"]
        labels["mos_sharpness"] = integrated_data["quality_sharpness_mos"]
        labels["mos_color_fidelity"] = integrated_data["quality_color_fidelity_mos"]

    # Create new enrichment version
    new_version = {
        "version": sample["enrichments"]["current_version"] + 1,
        "created_at": datetime.now(UTC).isoformat(),
        "created_by": f"integrate_diqa_enrichments.py_v{SCRIPT_VERSION}",
        "method": "multi_source_integration",
        "description": (
            "Integrated: LLM enrichment (domain, content), "
            "OpenLID (language), egret-xlarge layout (preferred) + "
            "Docling GPU fallback (layout, OCR), "
            "MOS scores, paper ground truth"
        ),
        "script_version": SCRIPT_VERSION,
        "data": integrated_data,
    }
    sample["enrichments"]["versions"].append(new_version)
    sample["enrichments"]["current_version"] = new_version["version"]


def run_integration(
    metadata: dict[str, Any],
    llm_index: dict[str, dict[str, Any]],
    lang_index: dict[str, dict[str, Any]],
    layout_index: dict[str, list[dict[str, Any]]],
    ocr_index: dict[str, dict[str, Any]],
    mos_index: dict[str, dict[str, float]],
    res_to_ori: dict[str, str],
    egret_index: dict[str, list[dict[str, Any]]] | None = None,
    orphan_corrections: dict[str, dict[str, Any]] | None = None,
    iqa_index: dict[str, dict[str, Any]] | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Run integration across all samples."""
    samples = metadata["samples"]
    total = len(samples)
    stats: dict[str, int] = Counter()

    log.info("Integrating enrichment data for %d samples ...", total)
    start = time.time()

    for idx, sample in enumerate(samples):
        filename = sample["source"]["original_filename"]

        integrated_data = integrate_sample(
            sample,
            llm_index,
            lang_index,
            layout_index,
            ocr_index,
            mos_index,
            res_to_ori,
            egret_index,
            orphan_corrections,
            iqa_index,
        )

        _track_source_matches(
            stats,
            filename,
            llm_index,
            lang_index,
            layout_index,
            ocr_index,
            mos_index,
            egret_index,
            iqa_index,
        )
        _track_distribution_stats(stats, integrated_data)

        if not dry_run:
            _apply_sample_enrichment(sample, integrated_data)

        if (idx + 1) % 500 == 0:
            elapsed = time.time() - start
            rate = (idx + 1) / elapsed
            log.info("  [%d/%d] %.0f samples/sec", idx + 1, total, rate)

    elapsed = time.time() - start
    log.info("Integration complete in %.1f seconds", elapsed)

    # Update top-level metadata
    if not dry_run:
        split_counts: dict[str, int] = Counter()
        for s in samples:
            split_counts[s["source"]["split"]] += 1
        metadata["splits_included"] = sorted(split_counts.keys())
        metadata["split_counts"] = dict(split_counts)

    return dict(stats)


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------
def print_summary(stats: dict[str, int], total: int) -> None:
    """Print integration summary."""
    print("\n" + "=" * 65)
    print("  DIQA-5000 Enrichment Integration Summary")
    print("=" * 65)
    print(f"  Total samples:       {total}")
    print("\n  Source match rates:")
    print(f"    LLM enrichment:    {stats.get('llm_matched', 0):>5d} / {total}")
    print(f"    Language (OpenLID): {stats.get('lang_matched', 0):>5d} / {total}")
    print(f"    Layout (egret):     {stats.get('egret_matched', 0):>5d} / {total}")
    print(f"    Layout (Docling):   {stats.get('layout_matched', 0):>5d} / {total}")
    print(f"    OCR (Docling):      {stats.get('ocr_matched', 0):>5d} / {total}")
    print(f"    MOS scores:         {stats.get('mos_matched', 0):>5d} / {total}")
    if stats.get("iqa_matched", 0) > 0:
        print(f"    Classical IQA:      {stats.get('iqa_matched', 0):>5d} / {total}")

    print("\n  Reliability distribution:")
    for cat in ["hard_label", "soft_label", "active_learning", "unreliable"]:
        count = stats.get(f"reliability_{cat}", 0)
        pct = count / total * 100 if total > 0 else 0
        print(f"    {cat:<20s} {count:>5d}  ({pct:5.1f}%)")

    # Language source breakdown
    print("\n  Language source breakdown:")
    for key, count in sorted(stats.items()):
        if key.startswith("lang_source_"):
            method = key.replace("lang_source_", "")
            pct = count / total * 100
            print(f"    {method:<40s} {count:>5d}  ({pct:5.1f}%)")

    # Domain source breakdown
    print("\n  Domain source breakdown:")
    for key, count in sorted(stats.items()):
        if key.startswith("domain_source_"):
            method = key.replace("domain_source_", "")
            pct = count / total * 100
            print(f"    {method:<40s} {count:>5d}  ({pct:5.1f}%)")

    # Split breakdown
    print("\n  Split distribution:")
    for key, count in sorted(stats.items()):
        if key.startswith("split_"):
            split_name = key.replace("split_", "")
            pct = count / total * 100
            print(f"    {split_name:<20s} {count:>5d}  ({pct:5.1f}%)")

    print("=" * 65 + "\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Integrate all enrichment sources into DIQA-5000 metadata.",
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=METADATA_PATH,
        help="Path to diqa-5000_metadata.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path (default: overwrite input file)",
    )
    parser.add_argument(
        "--egret-dir",
        type=Path,
        default=EGRET_BATCH_DIR,
        help="Path to egret batch output directory (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report only, do not write output",
    )
    parser.add_argument(
        "--run-classical-iqa",
        action="store_true",
        help="Run 8 classical IQA detectors on all images (slow, ~40ms/image). "
        "Results cached to --iqa-cache for future runs.",
    )
    parser.add_argument(
        "--iqa-cache",
        type=Path,
        default=IQA_CACHE_PATH,
        help="Path to classical IQA cache JSON (default: %(default)s)",
    )
    args = parser.parse_args()

    output_path = args.output or args.metadata

    # Load all data sources
    metadata = load_metadata(args.metadata)
    llm_index = load_llm_enrichment(LLM_ENRICHMENT_PATH)
    lang_index = load_language_enrichment(LANG_ENRICHMENT_PATH)
    layout_index = load_layout_batches(LAYOUT_BATCH_DIR)
    egret_index = load_egret_batches(args.egret_dir)
    ocr_index = load_ocr_batches(OCR_BATCH_DIR)
    mos_index, res_to_ori = load_mos_scores(DATASET_DIR)
    orphan_corr = load_orphan_corrections(ORPHAN_CORRECTIONS_PATH)

    # Classical IQA: run detectors or load from cache
    iqa_index: dict[str, dict[str, Any]] = {}
    if args.run_classical_iqa:
        iqa_index = run_classical_iqa_batch(metadata, DATASET_DIR, args.iqa_cache)
    else:
        iqa_index = load_classical_iqa_cache(args.iqa_cache)

    # Data leakage check: ensure no ori/ parent appears across multiple splits
    split_map: dict[str, str] = {}
    for s in metadata["samples"]:
        source = s.get("source", {})
        fname = source.get("original_filename", "")
        split_name = source.get("split", "")
        if fname and split_name:
            split_map[fname] = split_name

    leaks = check_split_leakage(res_to_ori, split_map)
    if leaks:
        log.warning(
            "DATA LEAKAGE: %d ori/ images appear in multiple splits: %s",
            len(leaks),
            leaks[:5],
        )
    else:
        log.info("Data leakage check: PASSED (no ori/ images cross splits)")

    # Run integration
    stats = run_integration(
        metadata=metadata,
        llm_index=llm_index,
        lang_index=lang_index,
        layout_index=layout_index,
        ocr_index=ocr_index,
        mos_index=mos_index,
        res_to_ori=res_to_ori,
        egret_index=egret_index or None,
        orphan_corrections=orphan_corr or None,
        iqa_index=iqa_index or None,
        dry_run=args.dry_run,
    )

    # Print summary
    print_summary(stats, len(metadata["samples"]))

    if args.dry_run:
        log.info("Dry run - no output written")
        return

    # Write output
    log.info("Writing integrated metadata to %s ...", output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as fh:
        json.dump(metadata, fh, indent=2, ensure_ascii=False)

    file_size_mb = output_path.stat().st_size / (1024 * 1024)
    log.info("  Written %.1f MB", file_size_mb)
    log.info("Done.")


if __name__ == "__main__":
    main()
